// Speaker notes, one entry per slide, in deck order. Slide numbers quoted in the notes go through
// S(n) (config.js), so they follow INTRO_SLIDES when the presenter puts slides in front of this deck.
// min: minutes on the slide · discuss: of which room discussion · from: minute the slide starts
// say: talking points · ask: a question for the room · tip: a delivery hint · next: the bridge to the next slide
const { S, PRESENTER, REPLY_BY } = require('./config.js');
module.exports = [
  { title: 'The round-table promise', min: 2, discuss: 0, from: 0,
    say: [
      'Open with the invite as published: this is a discussion, not a product demo.',
      'The gap it names: PlantUML and IDE plugins already check syntax (does it render?); nobody checks semantics (does it make sense?).',
      'Each paragraph opens one part of the session: ① the problem, ② what a linter contributes, ③ the value in our workflow, and your view throughout.',
      'Two small fixes against the published text: "uncharted" and "are not only".'],
    next: 'Here is how we get there: three questions.' },
  { title: 'Three questions for this round table', room: 'Warm-up: who writes, who builds on diagrams?', min: 2, discuss: 1, from: 2,
    say: [
      'Three questions, three outcomes: agree that there is a problem, understand what a semantic linter adds, decide whether a PoC is worth it.',
      'The chips are the keywords from the programme, sorted by the question they belong to.',
      'We end at a go / no-go for a PoC, not at adoption.'],
    ask: 'Warm-up, show of hands: who writes PlantUML diagrams? Who builds on someone else\'s diagram: a process, a design, code?',
    next: 'First, what we mean by semantic correctness.' },
  { title: 'What we mean by semantic correctness', min: 2, discuss: 0, from: 4,
    say: [
      'Syntax sits underneath and is solved: PlantUML tells you whether the file renders.',
      'Semantic correctness is six questions a reader would otherwise answer with a guess. Walk them with one example each.',
      '"Gaps" are Completeness, "ambiguities" are Ambiguity: together 55% of the score, and they decide whether a diagram is ready for hand-off.',
      'The percentages are the weights pumllint uses to combine the six into one score.'],
    next: 'Let\'s see it in practice: a credit flow.' },
  { title: 'Both render. Which branch approves?', min: 3, discuss: 1, from: 6, room: 'Which branch approves?',
    say: [
      'The first example: part of a credit flow as a process engineer would draw it, and the sequence diagram a designer derived from it. Both render.',
      'The process asks "Score sufficient?" but never says which branch is yes. The designer had to guess, and the guess shows up downstream as an alt block with no condition.',
      'pumllint reports both ends of the gap: ACT003 on the process (unlabelled branches) and SEQ007 on the sequence (alt without a condition). ACT002 adds that the process never reaches an end; it is major, so the build fails.',
      'pumllint does not know your credit policy. It flags that the diagram does not state it.'],
    ask: 'Before the reveal: which branch approves the credit? Then: who would have caught this today, and when?',
    tip: 'The findings strip appears on the next click: ask first, then click.',
    next: 'A second kind of problem only shows across diagrams.' },
  { title: 'Both render. Which one is right?', room: 'Which one is right?', min: 3, discuss: 2, from: 9,
    say: [
      'The second example: two files, each valid, each renders. The syntax layer is satisfied, file by file.',
      'Reveal the strip only after the room has answered. Read across both files, pumllint reports XD002, a Consistency finding: one entity, two stereotypes.',
      'It does not pick a side; it shows both places. A reviewer reading one file at a time never sees it.'],
    ask: 'Before the reveal: which one is right? Is OrderService a service with its own logic, or a gateway that passes calls through? Let two or three people answer.',
    tip: 'The XD002 strip appears on the next click: ask first, then click.',
    next: 'Why this matters: someone builds on every diagram.' },
  { title: 'Semantic quality: why it matters now', min: 2, discuss: 0, from: 12,
    say: [
      'The credit flow you just saw is one link of this chain. Walk it from left to right. The customer journey is not linted (there is no PlantUML journey type), so its gaps travel down unchecked.',
      'At every hand-off someone builds on the step before: process engineers and analysts, then analysts and AI tools, then developers and AI tools.',
      'Whatever is unclear becomes a guess; the guess becomes the foundation of the next step; in code it is an assumption that compiles and passes review.',
      'Filling gaps with guesses is not only an AI habit. AI raises the stakes: more volume, the same gaps, and it never asks.'],
    next: 'So how do we catch these gaps today?' },
  { title: 'Today: reviewed by eye, found late', room: 'Q1: how do you find gaps today?', min: 5, discuss: 3, from: 14,
    say: [
      'Same value stream as later in the deck, without a quality station: every hand-off relies on a review by eye.',
      'Gaps that pass it surface in code, test or production. The fix travels back to the business process, and every step built on the gap is redone.',
      'That growth in rework is expected from how the chain works; we have not measured it.'],
    ask: 'Question 1 on the slide: how do you find a diagram\'s gaps today, and at which step? Collect where, when and who.',
    next: 'What could a tool add here?' },
  { title: 'From linter to static model analysis', min: 2, discuss: 0, from: 19,
    say: [
      'A conventional linter matches patterns in text: line too long, unused variable.',
      `pumllint first turns each diagram into a model (who talks to whom, which flows, which states) and reasons over it, inside one diagram and across the whole set. Slide ${S(5)}'s finding only exists across files.`,
      'Detect, findings with a severity, is what any linter does. pumllint goes two steps further: measure (a maturity level per diagram and per set) and govern (a gate the team sets).',
      'Hence "static model analysis" rather than just a linter.'],
    next: 'What do those findings look like?' },
  { title: 'Code smells, model smells', min: 1, discuss: 0, from: 21,
    say: [
      'Borrow a term the room knows: a code smell is not always a bug, but it makes code harder to understand or trust.',
      'A model smell is the same for a diagram: not always an error, always a place where the next reader has to guess.',
      'One real rule per dimension, across diagram types. For process engineers, also ACT003: a decision whose branches are not labelled.',
      'Dark severity cells fail the build; the next slide shows what each severity does.'],
    next: 'What does each severity do?' },
  { title: 'Detect, measure, govern', min: 2, discuss: 0, from: 22,
    say: [
      'Detect: blocker, critical and major fail the build; minor and info are reported and lower the score.',
      'Measure: the findings add up to a level per diagram. Level 4, Precise, is the hand-off bar: the next step can build on it without guessing.',
      'Level 5 needs the stricter code-generation profile. It means the preconditions for AI code generation are met, not that the code will be right.',
      'Govern: the team picks the bar and the gate enforces it. For business processes, gate on findings: no ambiguity rule covers activity diagrams yet, so their level can look better than it is.',
      `Proof from slide ${S(4)}: the credit process scores Level 4 (Precise) while it carries a major finding that fails the build.`],
    next: 'Does the level actually matter?' },
  { title: 'Does the level matter? Measured: yes', min: 1, discuss: 0, from: 24,
    say: [
      'The one result we measured. AI tools generated code from sequence diagrams, and the code was run against acceptance tests written beforehand.',
      'From Level 1 diagrams about 1 in 3 intended behaviours failed; from Level 2 and up about 1 in 10. It held across three generators from two vendors and three prompt styles.',
      'Better prompting lifted moderately untidy diagrams, never the Level 1 ones: a prompt cannot add guards and failure paths the diagram never specified.',
      'Scope: sequence diagrams and AI-generated code only. Less rework and a shorter lead time are expected, not measured.'],
    tip: 'Source, if asked: EVIDENCE.md in the pumllint repository, section "What the product may claim"; the plain-English version is docs/evidence-explained.md, "Verdict 1".',
    next: 'If this sounds familiar, it should.' },
  { title: 'The same pattern you already trust on code', room: 'Q2: what may a tool decide?', min: 5, discuss: 3, from: 25,
    say: [
      'Compare them as linters, not by scope: both detect smells, rate what they find, gate on a threshold, and deal with existing debt without a big-bang cleanup.',
      'They meet in the pipeline: pumllint exports its findings in SonarQube\'s import format (-f sonar), so they appear on the same dashboard and in pull-request comments.',
      'SonarQube does not analyse the diagrams itself. The maturity level arrives there as one informational issue per diagram, so the gate on the level stays in pumllint.'],
    ask: 'Question 2 on the slide: which of these would you trust a tool to decide, and which stays a human review?',
    next: 'What would this change in our delivery?' },
  { title: 'Today, once more', min: 0, discuss: 0, from: 30,
    say: [
      `Click straight through: this is slide ${S(7)} again, so the Morph to the next slide shows exactly what changes.`],
    next: 'What the quality station changes.' },
  { title: 'Shift left: checked before it is built on', min: 3, discuss: 0, from: 30,
    say: [
      `Same value stream as slide ${S(7)}, same positions; two things changed.`,
      'Each diagram passes a quality station before the next step builds on it: syntax, the six dimensions, then a gate. Business processes are gated on their findings, solution designs on Level 4.',
      'The rework loop is gone: the author finds the gap while the fix is still small. Every author checks in the editor; every change is checked in CI.',
      `Evidence: the measured result from slide ${S(11)} (AI code from sequence diagrams). Less rework and shorter lead time are expected, not measured: a PoC is how we would find out.`],
    tip: `The Morph plays automatically from the recap slide (${S(13)}).`,
    next: 'How would we start?' },
  { title: 'Diagram quality, built into the workflow', room: 'PoC: what must it show? Where’s the gate?', min: 7, discuss: 5, from: 33,
    say: [
      'Two places, one tool. On your own machine: advice in the editor while you write, a full check from the command line with an HTML report.',
      'In the pipeline: a CI gate on every change, business processes converted from ARIS through the same gate, and dashboards, a report and a badge over time.',
      'Roll-out without a big-bang cleanup: advise (nothing fails), ratchet (nothing gets worse), floor (a minimum level).',
      'A PoC could start at step 1 on one team\'s diagrams.'],
    ask: 'The two closing questions: what would a PoC need to show to convince you? Where should the gate sit, and which level for which diagrams? Collect the answers: they become the success criteria of the PoC on the next slide.',
    next: 'Time to decide.' },
  { title: 'A PoC on semantic linting: go or no-go?', min: 4, discuss: 3, from: 40, room: 'Vote 👍 / 👎; if go: scope, criteria, owner, check-in',
    say: [
      'One line per part: diagrams render but not all make sense; a semantic linter finds model smells, measures maturity and gates the hand-off; it runs in the editor and in CI, starting with advice.',
      'Take the vote: thumbs up for go, thumbs down for no-go. Count both.',
      'If go, fill the four boxes before people leave: scope (one team, its diagrams), success criteria (from the answers on the previous slide), an owner with a timebox, and the date of the next check-in.',
      'If no-go, ask what would change people\'s minds and write it down: that is the input for a next attempt.'],
    ask: 'Thumbs up or thumbs down: do we run a PoC? Then, if go: who brings the diagrams, and what must the PoC show?' },
  { title: 'Appendix · A PoC on semantic linting: go or no-go?', handout: true, appendix: true, min: 0, discuss: 0, from: 44,
    say: [
      'Not presented: a one-page form for attendees to take back to their own squad or team lead, together with the three pumllint slides that follow.',
      'It carries the why in three lines, so a team lead who was not in the room can decide: team, contact, the answer (go, no-go, not yet) and, if go, the same four agreements as on the closing slide.',
      `Answers go back to ${PRESENTER} by ${REPLY_BY}; the address is in the lime strip.`],
    tip: `Send slides ${S(17)} to ${S(20)} as one PDF (team-handout.pdf), or print them.` },
  { title: 'Appendix · Get started in ten minutes', appendix: true, min: 0, discuss: 0, from: 44,
    say: ['Not presented: hand-out for the PoC team. Six commands from the README quick start cover a first run.'] },
  { title: 'Appendix · Fit it to your team', appendix: true, min: 0, discuss: 0, from: 44,
    say: ['Not presented: hand-out for the PoC team. One config file, a GitHub Action or pre-commit hooks, and the roll-out mapped to three commands.'] },
  { title: 'Appendix · A four-week PoC, and what to measure', appendix: true, min: 0, discuss: 0, from: 44,
    say: ['Not presented: hand-out for the PoC team. A suggested plan; the measures give the expected benefits a first measurement.'] },
];
